### ISSUE TITLE
Support a formatter?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#143]
@e-carlin writes:
> May be off topic but what about using something like [black](https://github.com/psf/black) so we can set our rules and don't have to teach them / talk about them in PRs? I've never used black but I've used [prettier](https://www.npmjs.com/package/prettier) in js projects and enjoyed it.

We are starting to get high on n^2 when communicating about such things so automation may be applicable. My concern is the time to set it up. I have tried to teach emacs all the rules, and it's still not right. 

I'm opinionated that name changes should not cause formatting changes. This is not typical, and some argue "just reformat!" but this runs into all kinds of issues, especially with version history comparisons.

I would be happy with a formatter, just not willing to take it on myself. Volunteers? Comments?

**Comment by e-carlin** [comment]
I'd like to use a formatter so I'll take it on. If people are familiar with python formatters please comment with any thoughts (ex black doesn't work well try xxx).

**Comment by e-carlin** [comment]
@robnagler can you provide more clarity on how name changes wouldn't cause a formatting change? In our current scheme if I change a name and the line is now > 100 chars that causes a formatting change. What should happen with a formatter?

**Comment by jeinstei** [comment]
`black` and `brunette` are my go-to formatters, as long as the options for extended lines are in the config; along with a good linter (`flake8`), I haven't had anything that causes me heartache, and they can all have configurations included in a Python project using modern packaging conventions. I like the enforced formatting as well, as even if people disagree as to if it is "good", having it standard with a well-supported tool is something that I value most. I've never seen everyone happy :D

Otherwise I haven't seen anything good out there aside from some one-offs using ANTLR (https://cucurbit.dev/posts/code-formatting-with-antlr-python/) or something else custom.

**Comment by robnagler** [comment]
> can you provide more clarity on how name changes wouldn't cause a formatting change?

This was about other styles and default styles in most formatters. The typical problem is this:

```py
some_function(first_arg,
              second_arg)
```

That's typically the default for continued lines in emacs in Python, Perl, and Lisp.

Linter is fine if you want to bother.

The real work is writing more tests, but formatting and linting are fine. :)

**Comment by robnagler** [comment]
@moellep @mkeilman @gurhar1133 @rorour please comment, thanks!

**Comment by mkeilman** [comment]
Not sure, TBH. I feel like there are a lot of exceptions. For example, arrays or lists with a handful of items are easier to read on one line. Templated html strings would suffer from line breaks. To say nothing of the method signature as mentioned above. How much control do we have, and how much time will we spend carving out exceptions?

Also, a lot of this formatting seems to replace horizontal space with vertical space, which is at a premium on modern monitors. Since that's what engendered this discussion in the first place, I have to wonder what the point is...

**Comment by jeinstei** [comment]
Just to argue the point (and keep the discussion in thread), the goal of consistent style and formatting is that there are no exceptions. Regardless of personal feelings, a consistent style is a choice made by the firm for consistency-- everything might not be as readable, but you'll at least know where it broke ([for example](https://github.com/psf/black/issues/2188)).

If the issue was line wrapping, just decide on a default width (160 or 180?) in all the tools? I always see this as the emacs vs vim debate -- no one really cares as long as the output is consistent. Or someone wrote a specialized function, and then you're using either one or the other because you have to.

**Comment by e-carlin** [comment]
> For example, arrays or lists with a handful of items are easier to read on one line

If we went with black I think it would do what you want [in this case](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#how-black-wraps-lines)

> How much control do we have, and how much time will we spend carving out exceptions?

It depends what formatter we pick. With black we ["cede control over minutiae of hand-formatting"](https://black.readthedocs.io/en/stable/index.html). For example, black uses [double-quotes over single quotes](https://github.com/psf/black/issues/118). Their advice for single quote users is to write single quotes and then have black come in after you and format them all to double quotes (in the past i've had my editors format on save). 

Josh mentioned [brunette](https://github.com/odwyersoftware/brunette). It uses black under the covers but then fixes some things like allowing single quotes. Strikes me as a bit absurd to use a formatter (black) and then have to use another formatter on top of it (brunette) to fix the problems of the first formatter. But I could be convinced otherwise.

Since we already nominally follow the google style guide we could maybe pick their formatter, [yapf](https://github.com/google/yapf#formatting-style). According to the docs it is very configurable. 

There are many others to choose from too...

> how much time will we spend carving out exceptions

I think this is up to us. My personal preference is no time. Just do what the formatter tells me. But, I don't hold that opinion very strongly. 

> a lot of this formatting seems to replace horizontal space with vertical space

I agree that this is a problem. But, at least black agrees too. The docs say, "As for vertical whitespace, Black tries to render one full expression or simple statement per line". I haven't investigated the other formatters enough to know.

If people feel strongly that a formatter is going to be too restrictive then I'm fine dropping this. I do think everyone should explore different formatters because I'm not going to be able to pick one that satisfies everyone.

**Comment by gurhar1133** [comment]
If it is easy to integrate into workflow, then I am down.

**Comment by robnagler** [comment]
> If it is easy to integrate into workflow, then I am down.

There are [issues with Black & PyCharm](https://youtrack.jetbrains.com/issue/PY-39750). If we use @e-carlin's model, then [configure as autosave should work](https://akshay-jain.medium.com/pycharm-black-with-formatting-on-auto-save-4797972cf5de). VSCode [seems to support various formatters including Black](https://code.visualstudio.com/docs/python/editing#_formatting). Emacs can do anything. :)

**Comment by robnagler** [comment]
is there a formatter that does js, bash, and python?

**Comment by jeinstei** [comment]
There's always adding it to the Megalinter:tm: (https://megalinter.github.io/5.3.0/)

**Comment by robnagler** [comment]
> There's always adding it to the Megalinter™️ (https://megalinter.github.io/5.3.0/)

The goal would be to speak one language, not multiple. Megalinter doesn't actually do the work so it's more CI/CD than linting afaict.

**Comment by jeinstei** [comment]
It's a question -- forcing code to run through a CI/CD chain when pushed for projects that are enforcing code style would also allow for autoformatting. That offloads the onus from the developer to the system to enforce policy, though. And it is better than using client-side hooks, imo

**Comment by robnagler** [comment]
I don't like automatic commits. I like knowing what I've tested in dev is exactly what gets to the build and release.

**Comment by robnagler** [comment]
One thing we need to be able to do is edit files in `~/.pyenv` without disturbing syntax so we can diff the file and the backup to know what we changed. home-env has [a special pattern](https://github.com/biviosoftware/home-env/blob/37f72eacaf74db9540c96a74ea1004d73d8c73e2/emacs.d/bivio-init.el#L138) for when to enable `delete-trailing-whitespace`. The same thing would have to be true for an automatic format on save.

**Comment by e-carlin** [comment]
For emacs users if we used something like https://github.com/wbolster/emacs-python-black#installation we would be able to add logic in the python-mode-hook to not enable python-black when we are in ~/.pyenv

**Comment by robnagler** [comment]
I like the idea of a proactive choice. You have to have a pyproject.toml that enables it.

**Comment by robnagler** [comment]
I'm good with this. The biggest change is single to double quotes.
