### ISSUE TITLE
pkcollections.mapping_merge() should do a deep merge

### ISSUE THREAD

**Issue by moellep** [radiasoft/pykern#21]
Currently mapping_merge() copies over key values. Instead, it should merge values with duplicate keys into a union. Merging should recurse so that a structure with values a.b.c.d merged with with a.b.c.z would contain both values:
```
{
  a: {
    b: {
      c: {
        d: v1,
        z: v2,
      }
    }
  }
}
```

**Comment by robnagler** [comment]
This is more complex, because there might be other data structures. rsconf solves this specifically for YAML merges with [merge_dict](https://github.com/radiasoft/rsconf/blob/c10009eec9faccaa49746589dec46faadf2aec8b/rsconf/db.py#L117), but this is very special, and has a key for overrides so you can cut out a tree of YAML config. 

Given the age of this request, I would say we can't change mapping_merge, and instead create a new routine. I don't know if it would be like rsconf.db.merge_dict or something else.
