### ISSUE TITLE
pkcli.ci ignore all dot-prefix dirs

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#215]
If there's a `.tox` directory, check_prints will fail. I don't think check_prints or run should look in dot prefixed files at all. There's a lot of them, and they don't contain anything we want to check regularly.

**Comment by gurhar1133** [comment]
I have been testing by doing
```bash
mkdir .x
vi x.py
```
writing a print in x.py
and then running
```bash
pykern ci check_prints
```
to confirm that what i did is working.

A unit test seems tricky however since case_dirs seems to ignore dot prefixed dirs. Should I try to write a test that manually writes a dot prefixed file to _work/ and then calls `check_prints` ? or is the `mkdir .x` method sufficient?

**Comment by robnagler** [comment]
Considering I just ran into a bug in exactly this thing. I think we might need a better test. One thing is to modify _EXCLUDE_FILES after ci is imported (before it is called) in a new test (ci1_test.py). This could remove _work from the regex (interesting problem :) so that _work won't be caught for this test only.
