### ISSUE TITLE
Use ruaml.yaml instead of pyyaml

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#83]
https://github.com/radiasoft/rsopt/issues/19 

There's a new API in 0.15

@cchall I'll implement this, which returns pkdict structures. Do you expect ordereddict?

**Comment by cchall** [comment]
Nothing in rsopt expects ordereddict. Some of the YAML read/write in rsbeams does assume that dict order (part of the reason that ruaml.yaml was used in rsbeams) is preserved, but uses native Python dict so that >Python3.6 is required for those features. Maybe this is not an ideal thing to do though?

**Comment by robnagler** [comment]
I think requiring ordering of the dict is probably a mistake. Normally, we sort keys if we want to enforce a specific ordering. Otherwise, you don't really want to depend on how the keys are read.
